# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/vitis_project/project_Lab_final/project_Lab_final.srcs/sources_1/ip/mmcm_fpro/mmcm_fpro.xci
# IP: The module: 'mmcm_fpro' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/vitis_project/project_Lab_final/project_Lab_final.srcs/sources_1/ip/mmcm_fpro/mmcm_fpro_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_fpro'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/vitis_project/project_Lab_final/project_Lab_final.srcs/sources_1/ip/mmcm_fpro/mmcm_fpro.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_fpro'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/vitis_project/project_Lab_final/project_Lab_final.srcs/sources_1/ip/mmcm_fpro/mmcm_fpro_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_fpro'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/vitis_project/project_Lab_final/project_Lab_final.srcs/sources_1/ip/mmcm_fpro/mmcm_fpro.xci
# IP: The module: 'mmcm_fpro' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/vitis_project/project_Lab_final/project_Lab_final.srcs/sources_1/ip/mmcm_fpro/mmcm_fpro_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_fpro'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/vitis_project/project_Lab_final/project_Lab_final.srcs/sources_1/ip/mmcm_fpro/mmcm_fpro.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_fpro'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/vitis_project/project_Lab_final/project_Lab_final.srcs/sources_1/ip/mmcm_fpro/mmcm_fpro_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_fpro'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
